"""empty message

Revision ID: 19a0a06fa8d5
Revises: e336ac8dfb6f
Create Date: 2021-07-12 18:48:55.912375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a0a06fa8d5'
down_revision = 'e336ac8dfb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Engine1', sa.Integer(), nullable=False),
    sa.Column('Engine2', sa.Integer(), nullable=False),
    sa.Column('Engine3', sa.Integer(), nullable=False),
    sa.Column('Engine4', sa.Integer(), nullable=False),
    sa.Column('Engine5', sa.Integer(), nullable=False),
    sa.Column('Engine6', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Remote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Direction', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Remote')
    op.drop_table('Engines')
    # ### end Alembic commands ###
