"""empty message

Revision ID: 728da9381615
Revises: cf59a824b23c
Create Date: 2021-07-12 15:34:05.621690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '728da9381615'
down_revision = 'cf59a824b23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Engine1', sa.Integer(), nullable=False),
    sa.Column('Engine2', sa.Integer(), nullable=False),
    sa.Column('Engine3', sa.Integer(), nullable=False),
    sa.Column('Engine4', sa.Integer(), nullable=False),
    sa.Column('Engine5', sa.Integer(), nullable=False),
    sa.Column('Engine6', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Remote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Direction', sa.String(10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engines',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Engine1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Engine2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Engine3', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Engine4', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Engine5', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Engine6', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Remote')
    op.drop_table('Engines')
    # ### end Alembic commands ###
