"""empty message

Revision ID: cf59a824b23c
Revises: 
Create Date: 2021-06-29 10:50:43.197423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf59a824b23c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Engine1', sa.Integer(), nullable=False),
    sa.Column('Engine2', sa.Integer(), nullable=False),
    sa.Column('Engine3', sa.Integer(), nullable=False),
    sa.Column('Engine4', sa.Integer(), nullable=False),
    sa.Column('Engine5', sa.Integer(), nullable=False),
    sa.Column('Engine6', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Engines')
    # ### end Alembic commands ###
