"""empty message

Revision ID: e336ac8dfb6f
Revises: 728da9381615
Create Date: 2021-07-12 15:37:07.097936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e336ac8dfb6f'
down_revision = '728da9381615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Engine1', sa.Integer(), nullable=False),
    sa.Column('Engine2', sa.Integer(), nullable=False),
    sa.Column('Engine3', sa.Integer(), nullable=False),
    sa.Column('Engine4', sa.Integer(), nullable=False),
    sa.Column('Engine5', sa.Integer(), nullable=False),
    sa.Column('Engine6', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Remote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Direction', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('remote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Direction', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Remote')
    op.drop_table('Engines')
    # ### end Alembic commands ###
